sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_install:
  # Setup Cargo path to make rustfmt available
  - source ~/.cargo/env
  # Check formatting
  - cargo install rustfmt
script:
  # Check build script formatting separately because cargo fmt doesn't pick it up
  - rustfmt --write-mode=diff build.rs
  # Check formatting of sources
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench --verbose
cache: cargo
