sudo: false
language: rust
# Don't cache; rust caches quickly grow so large in size that building
# everything anew is often faster than unpacking and repacking the cache.

script:
  - cargo build --verbose
  - cargo test --verbose

# Check formatting before running tests
stages:
  - formatting
  - test
  - lint
jobs:
  include:
    # Add an additional stage to check formatting
    - stage: formatting
      os: linux
      rust: stable
      before_install: rustup component add rustfmt-preview
      script: cargo fmt -- --check

      # Our target Rust version
    - stage: test
      os: linux
      rust: stable
    # Catch regressions in beta and nightly
    - stage: test
      os: linux
      rust: beta
    - stage: test
      os: linux
      rust: nightly

    # Run clippy after testing
    - stage: lint
      os: linux
      rust: stable
      before_install: rustup component add clippy-preview
      script: cargo clippy
