[package]
name = "xkpwgen"
version = "0.1.0-pre"
description = "Generate XKCD 936 passwords"
readme = "README.md"
homepage = "https://github.com/lunaryorn/xkpwgen.rs"
repository = "https://github.com/lunaryorn/xkpwgen.rs"
keywords = ["xkcd", "936", "password"]
categories = ["command-line-utilities", "text-processing"]
license = "GPL-3.0"
authors = ["Sebastian Wiesner <swiesner@lunaryorn.com>"]
build = "build.rs"

[package.metadata.release]
sign-commit = true
pre-release-commit-message = "Release {{version}}"
pro-release-commit-message = "Set version to {{version}}"
tag-message = "xkpwgen {{prefix}}-{{version}}"

[badges]
travis-ci = { repository = "https://github.com/lunaryorn/xkpwgen.rs" }

[dependencies]
rand = "^0.3"
clap = "^2.21"
ansi_term = "^0.9"
atty = "^0.2"

[build-dependencies]
sha2 = "^0.4"
reqwest = "^0.4"

[dev-dependencies]
quickcheck = "^0.4"

[[bin]]
doc = false
name = "xkpwgen"
