[package]
name = "xkpwgen"
version = "0.6.1-pre"
description = "Generate XKCD 936 passwords"
readme = "README.md"
homepage = "https://github.com/lunaryorn/xkpwgen.rs"
repository = "https://github.com/lunaryorn/xkpwgen.rs"
keywords = ["xkcd", "936", "password"]
categories = ["command-line-utilities", "text-processing"]
license = "Apache-2.0"
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]

[package.metadata.release]
sign-commit = true
pre-release-commit-message = "Release {{version}}"
pro-release-commit-message = "Set version to {{version}}"
tag-message = "xkpwgen {{prefix}}-{{version}}"

[badges]
travis-ci = { repository = "lunaryorn/xkpwgen.rs" }
maintenance = { status = "as-is" }

[dependencies]
rand = "^0.4"
clap = "^2.29"
structopt-derive = "^0.1"
structopt = "^0.1"
lazy_static = "^1.0"

[features]
default = []

[[bin]]
doc = false
name = "xkpwgen"
