[package]
name = "xkpwgen"
version = "0.8.1-alpha.0"
description = "Generate XKCD 936 passwords"
readme = "README.md"
homepage = "https://github.com/lunaryorn/xkpwgen.rs"
repository = "https://github.com/lunaryorn/xkpwgen.rs"
keywords = ["xkcd", "936", "password"]
categories = ["command-line-utilities", "text-processing"]
license = "Apache-2.0"
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]
edition = "2018"

[dependencies]
rand = "^0.7"
clap = "^2.33"
structopt-derive = "^0.3"
structopt = "^0.3"
lazy_static = "^1.4"

[features]
default = []

[[bin]]
doc = false
name = "xkpwgen"
